// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { getApiV1ApiKeysByApiKey, getApiV1KpUsersByIdVotes, getApiV1MediaPosts, getApiV1Persons, getApiV1Staff, getApiV1StaffById, getApiV21FilmsByIdSequelsAndPrequels, getApiV21FilmsSearchByKeyword, getApiV22Films, getApiV22FilmsById, getApiV22FilmsByIdAwards, getApiV22FilmsByIdBoxOffice, getApiV22FilmsByIdDistributions, getApiV22FilmsByIdExternalSources, getApiV22FilmsByIdFacts, getApiV22FilmsByIdImages, getApiV22FilmsByIdRelations, getApiV22FilmsByIdReviews, getApiV22FilmsByIdSeasons, getApiV22FilmsByIdSimilars, getApiV22FilmsByIdVideos, getApiV22FilmsCollections, getApiV22FilmsFilters, getApiV22FilmsPremieres, type Options } from '../sdk.gen';
import type { GetApiV1ApiKeysByApiKeyData, GetApiV1ApiKeysByApiKeyResponse, GetApiV1KpUsersByIdVotesData, GetApiV1KpUsersByIdVotesResponse, GetApiV1MediaPostsData, GetApiV1MediaPostsResponse, GetApiV1PersonsData, GetApiV1PersonsResponse, GetApiV1StaffByIdData, GetApiV1StaffByIdResponse, GetApiV1StaffData, GetApiV1StaffResponse, GetApiV21FilmsByIdSequelsAndPrequelsData, GetApiV21FilmsByIdSequelsAndPrequelsResponse, GetApiV21FilmsSearchByKeywordData, GetApiV21FilmsSearchByKeywordResponse, GetApiV22FilmsByIdAwardsData, GetApiV22FilmsByIdAwardsResponse, GetApiV22FilmsByIdBoxOfficeData, GetApiV22FilmsByIdBoxOfficeResponse, GetApiV22FilmsByIdData, GetApiV22FilmsByIdDistributionsData, GetApiV22FilmsByIdDistributionsResponse, GetApiV22FilmsByIdExternalSourcesData, GetApiV22FilmsByIdExternalSourcesResponse, GetApiV22FilmsByIdFactsData, GetApiV22FilmsByIdFactsResponse, GetApiV22FilmsByIdImagesData, GetApiV22FilmsByIdImagesResponse, GetApiV22FilmsByIdRelationsData, GetApiV22FilmsByIdRelationsResponse, GetApiV22FilmsByIdResponse, GetApiV22FilmsByIdReviewsData, GetApiV22FilmsByIdReviewsResponse, GetApiV22FilmsByIdSeasonsData, GetApiV22FilmsByIdSeasonsResponse, GetApiV22FilmsByIdSimilarsData, GetApiV22FilmsByIdSimilarsResponse, GetApiV22FilmsByIdVideosData, GetApiV22FilmsByIdVideosResponse, GetApiV22FilmsCollectionsData, GetApiV22FilmsCollectionsResponse, GetApiV22FilmsData, GetApiV22FilmsFiltersData, GetApiV22FilmsFiltersResponse, GetApiV22FilmsPremieresData, GetApiV22FilmsPremieresResponse, GetApiV22FilmsResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getApiV22FilmsByIdQueryKey = (options: Options<GetApiV22FilmsByIdData>) => createQueryKey('getApiV22FilmsById', options);

/**
 * получить данные о фильме по kinopoisk id
 *
 * Данный эндпоинт возвращает базовые данные о фильме. Поле <b>lastSync</b> показывает дату последнего обновления данных.
 */
export const getApiV22FilmsByIdOptions = (options: Options<GetApiV22FilmsByIdData>) => queryOptions<GetApiV22FilmsByIdResponse, DefaultError, GetApiV22FilmsByIdResponse, ReturnType<typeof getApiV22FilmsByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiV22FilmsById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiV22FilmsByIdQueryKey(options)
});

export const getApiV22FilmsByIdSeasonsQueryKey = (options: Options<GetApiV22FilmsByIdSeasonsData>) => createQueryKey('getApiV22FilmsByIdSeasons', options);

/**
 * получить данные о сезонах для сериала по kinopoisk film id
 *
 * Данный эндпоинт возвращает данные о сезонах для сериала.
 */
export const getApiV22FilmsByIdSeasonsOptions = (options: Options<GetApiV22FilmsByIdSeasonsData>) => queryOptions<GetApiV22FilmsByIdSeasonsResponse, DefaultError, GetApiV22FilmsByIdSeasonsResponse, ReturnType<typeof getApiV22FilmsByIdSeasonsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiV22FilmsByIdSeasons({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiV22FilmsByIdSeasonsQueryKey(options)
});

export const getApiV22FilmsByIdFactsQueryKey = (options: Options<GetApiV22FilmsByIdFactsData>) => createQueryKey('getApiV22FilmsByIdFacts', options);

/**
 * получить данные о фактах и ошибках в фильме по kinopoisk film id
 *
 * Данный эндпоинт возвращает список фактов и ошибок в фильме. <br> type - <b>FACT</b>, обозначает интересный факт о фильме. <br> type - <b>BLOOPER</b>, обозначает ошибку в фильме.
 */
export const getApiV22FilmsByIdFactsOptions = (options: Options<GetApiV22FilmsByIdFactsData>) => queryOptions<GetApiV22FilmsByIdFactsResponse, DefaultError, GetApiV22FilmsByIdFactsResponse, ReturnType<typeof getApiV22FilmsByIdFactsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiV22FilmsByIdFacts({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiV22FilmsByIdFactsQueryKey(options)
});

export const getApiV22FilmsByIdDistributionsQueryKey = (options: Options<GetApiV22FilmsByIdDistributionsData>) => createQueryKey('getApiV22FilmsByIdDistributions', options);

/**
 * получить данные о прокате фильма по kinopoisk film id
 *
 * Данный эндпоинт возвращает данные о прокате в разных странах.
 */
export const getApiV22FilmsByIdDistributionsOptions = (options: Options<GetApiV22FilmsByIdDistributionsData>) => queryOptions<GetApiV22FilmsByIdDistributionsResponse, DefaultError, GetApiV22FilmsByIdDistributionsResponse, ReturnType<typeof getApiV22FilmsByIdDistributionsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiV22FilmsByIdDistributions({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiV22FilmsByIdDistributionsQueryKey(options)
});

export const getApiV22FilmsByIdBoxOfficeQueryKey = (options: Options<GetApiV22FilmsByIdBoxOfficeData>) => createQueryKey('getApiV22FilmsByIdBoxOffice', options);

/**
 * получить данные о бюджете и сборах фильма по kinopoisk film id
 *
 * Данный эндпоинт возвращает данные о бюджете и сборах.
 */
export const getApiV22FilmsByIdBoxOfficeOptions = (options: Options<GetApiV22FilmsByIdBoxOfficeData>) => queryOptions<GetApiV22FilmsByIdBoxOfficeResponse, DefaultError, GetApiV22FilmsByIdBoxOfficeResponse, ReturnType<typeof getApiV22FilmsByIdBoxOfficeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiV22FilmsByIdBoxOffice({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiV22FilmsByIdBoxOfficeQueryKey(options)
});

export const getApiV22FilmsByIdAwardsQueryKey = (options: Options<GetApiV22FilmsByIdAwardsData>) => createQueryKey('getApiV22FilmsByIdAwards', options);

/**
 * получить данные о наградах фильма по kinopoisk film id
 *
 * Данный эндпоинт возвращает данные о наградах и премиях фильма.
 */
export const getApiV22FilmsByIdAwardsOptions = (options: Options<GetApiV22FilmsByIdAwardsData>) => queryOptions<GetApiV22FilmsByIdAwardsResponse, DefaultError, GetApiV22FilmsByIdAwardsResponse, ReturnType<typeof getApiV22FilmsByIdAwardsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiV22FilmsByIdAwards({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiV22FilmsByIdAwardsQueryKey(options)
});

export const getApiV22FilmsByIdVideosQueryKey = (options: Options<GetApiV22FilmsByIdVideosData>) => createQueryKey('getApiV22FilmsByIdVideos', options);

/**
 * получить трейлеры,тизеры,видео для фильма по kinopoisk film id
 *
 * Данный эндпоинт возвращает трейлеры,тизеры,видео для фильма по kinopoisk film id. В данный момент доступно три site:  <br/> <ul><li>YOUTUBE - в этом случае <b>url</b> это просто ссылка на youtube видео.</li><li>YANDEX_DISK - в этом случае <b>url</b> это ссылка на yandex disk.</li><li>KINOPOISK_WIDGET - в этом случае <b>url</b> это ссылка на кинопоиск виджет. <b>Видео доступно только с РФ ip</b>. Например https://widgets.kinopoisk.ru/discovery/trailer/123573?onlyPlayer=1&autoplay=1&cover=1. Если вы хотите вставить этот виджет на вашу страницу, вы можете сделать следующее:  <br/><br/>&lt;script src=&quot;https://unpkg.com/@ungap/custom-elements-builtin&quot;&gt;&lt;/script&gt;<br/>&lt;script type=&quot;module&quot; src=&quot;https://unpkg.com/x-frame-bypass&quot;&gt;&lt;/script&gt;<br/>&lt;iframe is=&quot;x-frame-bypass&quot; src=&quot;https://widgets.kinopoisk.ru/discovery/trailer/167560?onlyPlayer=1&amp;autoplay=1&amp;cover=1&quot; width=&quot;500&quot; height=&quot;500&quot;&gt;&lt;/iframe&gt;</li></ul>
 */
export const getApiV22FilmsByIdVideosOptions = (options: Options<GetApiV22FilmsByIdVideosData>) => queryOptions<GetApiV22FilmsByIdVideosResponse, DefaultError, GetApiV22FilmsByIdVideosResponse, ReturnType<typeof getApiV22FilmsByIdVideosQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiV22FilmsByIdVideos({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiV22FilmsByIdVideosQueryKey(options)
});

export const getApiV22FilmsByIdSimilarsQueryKey = (options: Options<GetApiV22FilmsByIdSimilarsData>) => createQueryKey('getApiV22FilmsByIdSimilars', options);

/**
 * получить список похожих фильмов по kinopoisk film id
 */
export const getApiV22FilmsByIdSimilarsOptions = (options: Options<GetApiV22FilmsByIdSimilarsData>) => queryOptions<GetApiV22FilmsByIdSimilarsResponse, DefaultError, GetApiV22FilmsByIdSimilarsResponse, ReturnType<typeof getApiV22FilmsByIdSimilarsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiV22FilmsByIdSimilars({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiV22FilmsByIdSimilarsQueryKey(options)
});

export const getApiV22FilmsByIdRelationsQueryKey = (options: Options<GetApiV22FilmsByIdRelationsData>) => createQueryKey('getApiV22FilmsByIdRelations', options);

/**
 * получить список связанных фильмов по kinopoisk film id
 */
export const getApiV22FilmsByIdRelationsOptions = (options: Options<GetApiV22FilmsByIdRelationsData>) => queryOptions<GetApiV22FilmsByIdRelationsResponse, DefaultError, GetApiV22FilmsByIdRelationsResponse, ReturnType<typeof getApiV22FilmsByIdRelationsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiV22FilmsByIdRelations({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiV22FilmsByIdRelationsQueryKey(options)
});

export const getApiV22FilmsByIdImagesQueryKey = (options: Options<GetApiV22FilmsByIdImagesData>) => createQueryKey('getApiV22FilmsByIdImages', options);

/**
 * получить изображения(кадры, постеры, фан-арты, обои и т.д.) связанные с фильмом по kinopoisk film id
 *
 * Данный эндпоинт возвращает изображения связанные с фильмом с пагинацией. Каждая страница содержит <b>не более чем 20 фильмов</b>.</br> Доступные изображения:</br> <ul> <li>STILL - кадры</li> <li>SHOOTING - изображения со съемок</li> <li>POSTER - постеры</li> <li>FAN_ART - фан-арты</li> <li>PROMO - промо</li> <li>CONCEPT - концепт-арты</li> <li>WALLPAPER - обои</li> <li>COVER - обложки</li> <li>SCREENSHOT - скриншоты</li> </ul>
 */
export const getApiV22FilmsByIdImagesOptions = (options: Options<GetApiV22FilmsByIdImagesData>) => queryOptions<GetApiV22FilmsByIdImagesResponse, DefaultError, GetApiV22FilmsByIdImagesResponse, ReturnType<typeof getApiV22FilmsByIdImagesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiV22FilmsByIdImages({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiV22FilmsByIdImagesQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const getApiV22FilmsByIdImagesInfiniteQueryKey = (options: Options<GetApiV22FilmsByIdImagesData>): QueryKey<Options<GetApiV22FilmsByIdImagesData>> => createQueryKey('getApiV22FilmsByIdImages', options, true);

/**
 * получить изображения(кадры, постеры, фан-арты, обои и т.д.) связанные с фильмом по kinopoisk film id
 *
 * Данный эндпоинт возвращает изображения связанные с фильмом с пагинацией. Каждая страница содержит <b>не более чем 20 фильмов</b>.</br> Доступные изображения:</br> <ul> <li>STILL - кадры</li> <li>SHOOTING - изображения со съемок</li> <li>POSTER - постеры</li> <li>FAN_ART - фан-арты</li> <li>PROMO - промо</li> <li>CONCEPT - концепт-арты</li> <li>WALLPAPER - обои</li> <li>COVER - обложки</li> <li>SCREENSHOT - скриншоты</li> </ul>
 */
export const getApiV22FilmsByIdImagesInfiniteOptions = (options: Options<GetApiV22FilmsByIdImagesData>) => infiniteQueryOptions<GetApiV22FilmsByIdImagesResponse, DefaultError, InfiniteData<GetApiV22FilmsByIdImagesResponse>, QueryKey<Options<GetApiV22FilmsByIdImagesData>>, number | Pick<QueryKey<Options<GetApiV22FilmsByIdImagesData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetApiV22FilmsByIdImagesData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getApiV22FilmsByIdImages({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiV22FilmsByIdImagesInfiniteQueryKey(options)
});

export const getApiV22FilmsByIdReviewsQueryKey = (options: Options<GetApiV22FilmsByIdReviewsData>) => createQueryKey('getApiV22FilmsByIdReviews', options);

/**
 * получить список рецензии зрителей по kinopoisk film id
 *
 * Возвращает список рецензии зрителей с пагинацией. Каждая страница содержит не более чем 20 рецензий.
 */
export const getApiV22FilmsByIdReviewsOptions = (options: Options<GetApiV22FilmsByIdReviewsData>) => queryOptions<GetApiV22FilmsByIdReviewsResponse, DefaultError, GetApiV22FilmsByIdReviewsResponse, ReturnType<typeof getApiV22FilmsByIdReviewsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiV22FilmsByIdReviews({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiV22FilmsByIdReviewsQueryKey(options)
});

export const getApiV22FilmsByIdReviewsInfiniteQueryKey = (options: Options<GetApiV22FilmsByIdReviewsData>): QueryKey<Options<GetApiV22FilmsByIdReviewsData>> => createQueryKey('getApiV22FilmsByIdReviews', options, true);

/**
 * получить список рецензии зрителей по kinopoisk film id
 *
 * Возвращает список рецензии зрителей с пагинацией. Каждая страница содержит не более чем 20 рецензий.
 */
export const getApiV22FilmsByIdReviewsInfiniteOptions = (options: Options<GetApiV22FilmsByIdReviewsData>) => infiniteQueryOptions<GetApiV22FilmsByIdReviewsResponse, DefaultError, InfiniteData<GetApiV22FilmsByIdReviewsResponse>, QueryKey<Options<GetApiV22FilmsByIdReviewsData>>, number | Pick<QueryKey<Options<GetApiV22FilmsByIdReviewsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetApiV22FilmsByIdReviewsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getApiV22FilmsByIdReviews({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiV22FilmsByIdReviewsInfiniteQueryKey(options)
});

export const getApiV22FilmsByIdExternalSourcesQueryKey = (options: Options<GetApiV22FilmsByIdExternalSourcesData>) => createQueryKey('getApiV22FilmsByIdExternalSources', options);

/**
 * получить список сайтов, где можно посмотреть фильм по kinopoisk film id
 *
 * Возвращает список сайтов с пагинацией. Каждая страница содержит не более чем 20 рецензий.
 */
export const getApiV22FilmsByIdExternalSourcesOptions = (options: Options<GetApiV22FilmsByIdExternalSourcesData>) => queryOptions<GetApiV22FilmsByIdExternalSourcesResponse, DefaultError, GetApiV22FilmsByIdExternalSourcesResponse, ReturnType<typeof getApiV22FilmsByIdExternalSourcesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiV22FilmsByIdExternalSources({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiV22FilmsByIdExternalSourcesQueryKey(options)
});

export const getApiV22FilmsByIdExternalSourcesInfiniteQueryKey = (options: Options<GetApiV22FilmsByIdExternalSourcesData>): QueryKey<Options<GetApiV22FilmsByIdExternalSourcesData>> => createQueryKey('getApiV22FilmsByIdExternalSources', options, true);

/**
 * получить список сайтов, где можно посмотреть фильм по kinopoisk film id
 *
 * Возвращает список сайтов с пагинацией. Каждая страница содержит не более чем 20 рецензий.
 */
export const getApiV22FilmsByIdExternalSourcesInfiniteOptions = (options: Options<GetApiV22FilmsByIdExternalSourcesData>) => infiniteQueryOptions<GetApiV22FilmsByIdExternalSourcesResponse, DefaultError, InfiniteData<GetApiV22FilmsByIdExternalSourcesResponse>, QueryKey<Options<GetApiV22FilmsByIdExternalSourcesData>>, number | Pick<QueryKey<Options<GetApiV22FilmsByIdExternalSourcesData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetApiV22FilmsByIdExternalSourcesData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getApiV22FilmsByIdExternalSources({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiV22FilmsByIdExternalSourcesInfiniteQueryKey(options)
});

export const getApiV22FilmsCollectionsQueryKey = (options?: Options<GetApiV22FilmsCollectionsData>) => createQueryKey('getApiV22FilmsCollections', options);

/**
 * получить список фильмов из различных топов или коллекций. Например https://www.kinopoisk.ru/top/lists/58/
 *
 * Возвращает список фильмов с пагинацией. Каждая страница содержит не более чем 20 фильмов.
 */
export const getApiV22FilmsCollectionsOptions = (options?: Options<GetApiV22FilmsCollectionsData>) => queryOptions<GetApiV22FilmsCollectionsResponse, DefaultError, GetApiV22FilmsCollectionsResponse, ReturnType<typeof getApiV22FilmsCollectionsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiV22FilmsCollections({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiV22FilmsCollectionsQueryKey(options)
});

export const getApiV22FilmsCollectionsInfiniteQueryKey = (options?: Options<GetApiV22FilmsCollectionsData>): QueryKey<Options<GetApiV22FilmsCollectionsData>> => createQueryKey('getApiV22FilmsCollections', options, true);

/**
 * получить список фильмов из различных топов или коллекций. Например https://www.kinopoisk.ru/top/lists/58/
 *
 * Возвращает список фильмов с пагинацией. Каждая страница содержит не более чем 20 фильмов.
 */
export const getApiV22FilmsCollectionsInfiniteOptions = (options?: Options<GetApiV22FilmsCollectionsData>) => infiniteQueryOptions<GetApiV22FilmsCollectionsResponse, DefaultError, InfiniteData<GetApiV22FilmsCollectionsResponse>, QueryKey<Options<GetApiV22FilmsCollectionsData>>, number | Pick<QueryKey<Options<GetApiV22FilmsCollectionsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetApiV22FilmsCollectionsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getApiV22FilmsCollections({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiV22FilmsCollectionsInfiniteQueryKey(options)
});

export const getApiV22FilmsPremieresQueryKey = (options: Options<GetApiV22FilmsPremieresData>) => createQueryKey('getApiV22FilmsPremieres', options);

/**
 * получить список кинопремьер
 *
 * Данный эндпоинт возвращает список кинопремьер. Например https://www.kinopoisk.ru/premiere/
 */
export const getApiV22FilmsPremieresOptions = (options: Options<GetApiV22FilmsPremieresData>) => queryOptions<GetApiV22FilmsPremieresResponse, DefaultError, GetApiV22FilmsPremieresResponse, ReturnType<typeof getApiV22FilmsPremieresQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiV22FilmsPremieres({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiV22FilmsPremieresQueryKey(options)
});

export const getApiV22FilmsFiltersQueryKey = (options?: Options<GetApiV22FilmsFiltersData>) => createQueryKey('getApiV22FilmsFilters', options);

/**
 * получить id стран и жанров для использования в /api/v2.2/films
 *
 * Возвращает список id стран и жанров, которые могут быть использованы в /api/v2.2/films
 */
export const getApiV22FilmsFiltersOptions = (options?: Options<GetApiV22FilmsFiltersData>) => queryOptions<GetApiV22FilmsFiltersResponse, DefaultError, GetApiV22FilmsFiltersResponse, ReturnType<typeof getApiV22FilmsFiltersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiV22FilmsFilters({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiV22FilmsFiltersQueryKey(options)
});

export const getApiV22FilmsQueryKey = (options?: Options<GetApiV22FilmsData>) => createQueryKey('getApiV22Films', options);

/**
 * получить список фильмов по различным фильтрам
 *
 * Возвращает список фильмов с пагинацией. Каждая страница содержит не более чем 20 фильмов. Данный эндпоинт не возращает более 400 фильмов. <i>Используй /api/v2.2/films/filters чтобы получить id стран и жанров.</i>
 */
export const getApiV22FilmsOptions = (options?: Options<GetApiV22FilmsData>) => queryOptions<GetApiV22FilmsResponse, DefaultError, GetApiV22FilmsResponse, ReturnType<typeof getApiV22FilmsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiV22Films({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiV22FilmsQueryKey(options)
});

export const getApiV22FilmsInfiniteQueryKey = (options?: Options<GetApiV22FilmsData>): QueryKey<Options<GetApiV22FilmsData>> => createQueryKey('getApiV22Films', options, true);

/**
 * получить список фильмов по различным фильтрам
 *
 * Возвращает список фильмов с пагинацией. Каждая страница содержит не более чем 20 фильмов. Данный эндпоинт не возращает более 400 фильмов. <i>Используй /api/v2.2/films/filters чтобы получить id стран и жанров.</i>
 */
export const getApiV22FilmsInfiniteOptions = (options?: Options<GetApiV22FilmsData>) => infiniteQueryOptions<GetApiV22FilmsResponse, DefaultError, InfiniteData<GetApiV22FilmsResponse>, QueryKey<Options<GetApiV22FilmsData>>, number | Pick<QueryKey<Options<GetApiV22FilmsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetApiV22FilmsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getApiV22Films({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiV22FilmsInfiniteQueryKey(options)
});

export const getApiV21FilmsByIdSequelsAndPrequelsQueryKey = (options: Options<GetApiV21FilmsByIdSequelsAndPrequelsData>) => createQueryKey('getApiV21FilmsByIdSequelsAndPrequels', options);

/**
 * получить сиквелы и приквелы для фильма по kinopoisk film id
 *
 * tbd
 */
export const getApiV21FilmsByIdSequelsAndPrequelsOptions = (options: Options<GetApiV21FilmsByIdSequelsAndPrequelsData>) => queryOptions<GetApiV21FilmsByIdSequelsAndPrequelsResponse, DefaultError, GetApiV21FilmsByIdSequelsAndPrequelsResponse, ReturnType<typeof getApiV21FilmsByIdSequelsAndPrequelsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiV21FilmsByIdSequelsAndPrequels({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiV21FilmsByIdSequelsAndPrequelsQueryKey(options)
});

export const getApiV21FilmsSearchByKeywordQueryKey = (options: Options<GetApiV21FilmsSearchByKeywordData>) => createQueryKey('getApiV21FilmsSearchByKeyword', options);

/**
 * получить список фильмов по ключевым словам
 *
 * Возвращает список фильмов с пагинацией. Каждая страница содержит не более чем 20 фильмов.
 */
export const getApiV21FilmsSearchByKeywordOptions = (options: Options<GetApiV21FilmsSearchByKeywordData>) => queryOptions<GetApiV21FilmsSearchByKeywordResponse, DefaultError, GetApiV21FilmsSearchByKeywordResponse, ReturnType<typeof getApiV21FilmsSearchByKeywordQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiV21FilmsSearchByKeyword({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiV21FilmsSearchByKeywordQueryKey(options)
});

export const getApiV21FilmsSearchByKeywordInfiniteQueryKey = (options: Options<GetApiV21FilmsSearchByKeywordData>): QueryKey<Options<GetApiV21FilmsSearchByKeywordData>> => createQueryKey('getApiV21FilmsSearchByKeyword', options, true);

/**
 * получить список фильмов по ключевым словам
 *
 * Возвращает список фильмов с пагинацией. Каждая страница содержит не более чем 20 фильмов.
 */
export const getApiV21FilmsSearchByKeywordInfiniteOptions = (options: Options<GetApiV21FilmsSearchByKeywordData>) => infiniteQueryOptions<GetApiV21FilmsSearchByKeywordResponse, DefaultError, InfiniteData<GetApiV21FilmsSearchByKeywordResponse>, QueryKey<Options<GetApiV21FilmsSearchByKeywordData>>, number | Pick<QueryKey<Options<GetApiV21FilmsSearchByKeywordData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetApiV21FilmsSearchByKeywordData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getApiV21FilmsSearchByKeyword({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiV21FilmsSearchByKeywordInfiniteQueryKey(options)
});

export const getApiV1StaffQueryKey = (options: Options<GetApiV1StaffData>) => createQueryKey('getApiV1Staff', options);

/**
 * получить данные об актерах, режисерах и т.д. по kinopoisk film id
 */
export const getApiV1StaffOptions = (options: Options<GetApiV1StaffData>) => queryOptions<GetApiV1StaffResponse, DefaultError, GetApiV1StaffResponse, ReturnType<typeof getApiV1StaffQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiV1Staff({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiV1StaffQueryKey(options)
});

export const getApiV1StaffByIdQueryKey = (options: Options<GetApiV1StaffByIdData>) => createQueryKey('getApiV1StaffById', options);

/**
 * получить данные о конкретном человеке по kinopoisk person id
 */
export const getApiV1StaffByIdOptions = (options: Options<GetApiV1StaffByIdData>) => queryOptions<GetApiV1StaffByIdResponse, DefaultError, GetApiV1StaffByIdResponse, ReturnType<typeof getApiV1StaffByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiV1StaffById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiV1StaffByIdQueryKey(options)
});

export const getApiV1PersonsQueryKey = (options: Options<GetApiV1PersonsData>) => createQueryKey('getApiV1Persons', options);

/**
 * поиск актеров, режиссеров и т.д. по имени
 *
 * Одна страница может содержать до 50 элементов в items.
 */
export const getApiV1PersonsOptions = (options: Options<GetApiV1PersonsData>) => queryOptions<GetApiV1PersonsResponse, DefaultError, GetApiV1PersonsResponse, ReturnType<typeof getApiV1PersonsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiV1Persons({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiV1PersonsQueryKey(options)
});

export const getApiV1PersonsInfiniteQueryKey = (options: Options<GetApiV1PersonsData>): QueryKey<Options<GetApiV1PersonsData>> => createQueryKey('getApiV1Persons', options, true);

/**
 * поиск актеров, режиссеров и т.д. по имени
 *
 * Одна страница может содержать до 50 элементов в items.
 */
export const getApiV1PersonsInfiniteOptions = (options: Options<GetApiV1PersonsData>) => infiniteQueryOptions<GetApiV1PersonsResponse, DefaultError, InfiniteData<GetApiV1PersonsResponse>, QueryKey<Options<GetApiV1PersonsData>>, number | Pick<QueryKey<Options<GetApiV1PersonsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetApiV1PersonsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getApiV1Persons({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiV1PersonsInfiniteQueryKey(options)
});

export const getApiV1KpUsersByIdVotesQueryKey = (options: Options<GetApiV1KpUsersByIdVotesData>) => createQueryKey('getApiV1KpUsersByIdVotes', options);

/**
 * получить данные об оценках пользователя
 *
 * Одна страница может содержать до 20 элементов в items. Доступны не все оценки пользователя, а примерно 1500 последних
 */
export const getApiV1KpUsersByIdVotesOptions = (options: Options<GetApiV1KpUsersByIdVotesData>) => queryOptions<GetApiV1KpUsersByIdVotesResponse, DefaultError, GetApiV1KpUsersByIdVotesResponse, ReturnType<typeof getApiV1KpUsersByIdVotesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiV1KpUsersByIdVotes({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiV1KpUsersByIdVotesQueryKey(options)
});

export const getApiV1KpUsersByIdVotesInfiniteQueryKey = (options: Options<GetApiV1KpUsersByIdVotesData>): QueryKey<Options<GetApiV1KpUsersByIdVotesData>> => createQueryKey('getApiV1KpUsersByIdVotes', options, true);

/**
 * получить данные об оценках пользователя
 *
 * Одна страница может содержать до 20 элементов в items. Доступны не все оценки пользователя, а примерно 1500 последних
 */
export const getApiV1KpUsersByIdVotesInfiniteOptions = (options: Options<GetApiV1KpUsersByIdVotesData>) => infiniteQueryOptions<GetApiV1KpUsersByIdVotesResponse, DefaultError, InfiniteData<GetApiV1KpUsersByIdVotesResponse>, QueryKey<Options<GetApiV1KpUsersByIdVotesData>>, number | Pick<QueryKey<Options<GetApiV1KpUsersByIdVotesData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetApiV1KpUsersByIdVotesData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getApiV1KpUsersByIdVotes({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiV1KpUsersByIdVotesInfiniteQueryKey(options)
});

export const getApiV1ApiKeysByApiKeyQueryKey = (options: Options<GetApiV1ApiKeysByApiKeyData>) => createQueryKey('getApiV1ApiKeysByApiKey', options);

/**
 * получить данные об api key
 */
export const getApiV1ApiKeysByApiKeyOptions = (options: Options<GetApiV1ApiKeysByApiKeyData>) => queryOptions<GetApiV1ApiKeysByApiKeyResponse, DefaultError, GetApiV1ApiKeysByApiKeyResponse, ReturnType<typeof getApiV1ApiKeysByApiKeyQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiV1ApiKeysByApiKey({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiV1ApiKeysByApiKeyQueryKey(options)
});

export const getApiV1MediaPostsQueryKey = (options?: Options<GetApiV1MediaPostsData>) => createQueryKey('getApiV1MediaPosts', options);

/**
 * получить медиа новости с сайта кинопоиск
 *
 * Одна страница может содержать до 20 элементов в items.
 */
export const getApiV1MediaPostsOptions = (options?: Options<GetApiV1MediaPostsData>) => queryOptions<GetApiV1MediaPostsResponse, DefaultError, GetApiV1MediaPostsResponse, ReturnType<typeof getApiV1MediaPostsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiV1MediaPosts({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiV1MediaPostsQueryKey(options)
});

export const getApiV1MediaPostsInfiniteQueryKey = (options?: Options<GetApiV1MediaPostsData>): QueryKey<Options<GetApiV1MediaPostsData>> => createQueryKey('getApiV1MediaPosts', options, true);

/**
 * получить медиа новости с сайта кинопоиск
 *
 * Одна страница может содержать до 20 элементов в items.
 */
export const getApiV1MediaPostsInfiniteOptions = (options?: Options<GetApiV1MediaPostsData>) => infiniteQueryOptions<GetApiV1MediaPostsResponse, DefaultError, InfiniteData<GetApiV1MediaPostsResponse>, QueryKey<Options<GetApiV1MediaPostsData>>, number | Pick<QueryKey<Options<GetApiV1MediaPostsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetApiV1MediaPostsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getApiV1MediaPosts({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiV1MediaPostsInfiniteQueryKey(options)
});
