import { defineConfig } from 'oxlint'

export default defineConfig({
	categories: {
		correctness: 'off',
	},

	env: {
		browser: true,
		builtin: true,
		es2024: true,
		node: true,
	},

	ignorePatterns: ['public', 'src/common/api/codegen'],

	jsPlugins: [
		'@nkzw/eslint-plugin',
		'eslint-plugin-perfectionist',
		{ name: 'react-hooks-js', specifier: 'eslint-plugin-react-hooks' },
	],

	options: {
		typeAware: true,
	},

	plugins: ['eslint', 'typescript', 'unicorn', 'react', 'oxc', 'import', 'jsx-a11y'],

	rules: {
		'@nkzw/ensure-relay-types': 'error',
		'@nkzw/no-instanceof': 'error',
		'@nkzw/require-use-effect-arguments': 'error',

		complexity: 'off',
		'constructor-super': 'error',
		curly: ['warn', 'multi-line'],
		'for-direction': 'error',
		'getter-return': 'error',
		'import/consistent-type-specifier-style': 'off',
		'import/export': 'error',
		'import/no-default-export': 'off',
		'import/no-named-export': 'off',
		'import/no-namespace': 'error',
		'import/prefer-default-export': 'off',
		'import/unambiguous': 'off',
		'no-array-constructor': 'error',
		'no-async-promise-executor': 'error',
		'no-caller': 'error',
		'no-case-declarations': 'error',
		'no-class-assign': 'error',
		'no-compare-neg-zero': 'error',
		'no-cond-assign': 'error',
		'no-const-assign': 'error',
		'no-constant-binary-expression': 'error',
		'no-constant-condition': 'error',
		'no-control-regex': 'error',
		'no-debugger': 'error',
		'no-delete-var': 'error',
		'no-dupe-class-members': 'error',
		'no-dupe-else-if': 'error',
		'no-dupe-keys': 'error',
		'no-duplicate-case': 'error',
		'no-duplicate-imports': 'error',
		'no-else-return': 'error',
		'no-empty': 'off',
		'no-empty-character-class': 'error',
		'no-empty-pattern': 'off',
		'no-empty-static-block': 'error',
		'no-ex-assign': 'error',
		'no-extra-boolean-cast': 'error',
		'no-fallthrough': 'error',
		'no-func-assign': 'error',
		'no-global-assign': 'error',
		'no-import-assign': 'error',
		'no-import-type-side-effect': 'off',
		'no-invalid-regexp': 'error',
		'no-irregular-whitespace': 'error',
		'no-iterator': 'error',
		'no-lonely-if': 'error',
		'no-loss-of-precision': 'error',
		'no-misleading-character-class': 'error',
		'no-multi-str': 'warn',
		'no-new-native-nonconstructor': 'error',
		'no-new-wrappers': 'error',
		'no-nonoctal-decimal-escape': 'error',
		'no-obj-calls': 'error',
		'no-proto': 'error',
		'no-prototype-builtins': 'error',
		'no-redeclare': 'error',
		'no-regex-spaces': 'error',
		'no-self-assign': 'error',
		'no-setter-return': 'error',
		'no-shadow': 'off',
		'no-shadow-restricted-names': 'error',
		'no-sparse-arrays': 'error',
		'no-this-before-super': 'error',
		'no-undef': 'error',
		'no-undef-init': 'error',
		'no-unexpected-multiline': 'error',
		'no-unneeded-ternary': 'error',
		'no-unreachable': 'error',
		'no-unsafe-finally': 'error',
		'no-unsafe-negation': 'error',
		'no-unsafe-optional-chaining': 'error',
		'no-unused-expressions': 'error',
		'no-unused-labels': 'error',
		'no-unused-private-class-members': 'error',
		'no-unused-vars': [
			'warn',
			{
				args: 'after-used',
				argsIgnorePattern: '^_',
				caughtErrorsIgnorePattern: '^_',
				ignoreRestSiblings: true,
				varsIgnorePattern: '^_',
			},
		],
		'no-useless-backreference': 'error',
		'no-useless-call': 'warn',
		'no-useless-catch': 'error',
		'no-useless-computed-key': 'warn',
		'no-useless-concat': 'warn',
		'no-useless-constructor': 'warn',
		'no-useless-escape': 'warn',
		'no-useless-rename': 'warn',
		'no-var': 'warn',
		'no-warning-comments': [
			'error',
			{
				terms: ['@nocommit'],
			},
		],
		'no-with': 'error',
		'object-shorthand': 'warn',
		'perfectionist/sort-enums': [
			'error',
			{
				partitionByComment: true,
				sortByValue: 'always',
			},
		],
		'perfectionist/sort-heritage-clauses': 'error',
		'perfectionist/sort-interfaces': 'error',
		'perfectionist/sort-jsx-props': 'error',
		'perfectionist/sort-object-types': 'error',
		'prefer-arrow-callback': 'warn',
		'prefer-const': 'error',
		'prefer-rest-params': 'warn',
		'prefer-spread': 'warn',
		'prefer-template': 'warn',
		quotes: [
			'off',
			'single',
			{
				allowTemplateLiterals: true,
				avoidEscape: true,
			},
		],
		radix: 'warn',
		'react-hooks-js/component-hook-factories': 'error',
		'react-hooks-js/config': 'error',
		'react-hooks-js/error-boundaries': 'error',
		'react-hooks-js/gating': 'error',
		'react-hooks-js/globals': 'error',
		'react-hooks-js/immutability': 'error',
		'react-hooks-js/incompatible-library': 'error',
		'react-hooks-js/preserve-manual-memoization': 'error',
		'react-hooks-js/purity': 'error',
		'react-hooks-js/refs': 'error',
		'react-hooks-js/set-state-in-effect': 'error',
		'react-hooks-js/set-state-in-render': 'error',
		'react-hooks-js/static-components': 'error',
		'react-hooks-js/unsupported-syntax': 'error',
		'react-hooks-js/use-memo': 'error',
		'react/display-name': 'error',
		'react/exhaustive-deps': 'error',
		'react/jsx-key': 'error',
		'react/jsx-no-comment-textnodes': 'error',
		'react/jsx-no-duplicate-props': 'error',
		'react/jsx-no-target-blank': 'error',
		'react/jsx-no-undef': 'error',
		'react/no-children-prop': 'error',
		'react/no-danger-with-children': 'error',
		'react/no-direct-mutation-state': 'error',
		'react/no-find-dom-node': 'error',
		'react/no-is-mounted': 'error',
		'react/no-render-return-value': 'error',
		'react/no-string-refs': 'error',
		'react/no-unescaped-entities': 'error',
		'react/no-unknown-property': 'error',
		'react/require-render-return': 'error',
		'require-yield': 'error',
		'sort-imports': 'off',
		'sort-keys': ['warn', 'asc', { natural: true }],
		strict: ['error', 'never'],
		'typescript/array-type': [
			'error',
			{
				default: 'generic',
			},
		],
		'typescript/dot-notation': [
			'error',
			{
				allowKeywords: true,
			},
		],
		'typescript/explicit-module-boundary-types': 'off',
		'typescript/no-dupe-class-members': 'error',
		'typescript/no-duplicate-enum-values': 'error',
		'typescript/no-dynamic-delete': 'off',
		'typescript/no-empty-object-type': 'error',
		'typescript/no-explicit-any': 'error',
		'typescript/no-extra-non-null-assertion': 'error',
		'typescript/no-import-type-side-effects': 'error',
		'typescript/no-invalid-this': ['error', { capIsConstructor: true }],
		'typescript/no-invalid-void-type': 'off',
		'typescript/no-misused-new': 'error',
		'typescript/no-misused-promises': 'off',
		'typescript/no-non-null-asserted-optional-chain': 'error',
		'typescript/no-non-null-assertion': 'off',
		'typescript/no-redeclare': 'error',
		'typescript/no-require-imports': 'error',
		'typescript/no-unnecessary-type-constraint': 'error',
		'typescript/no-unnecessary-type-conversion': 'error',
		'typescript/no-unnecessary-type-parameters': 'off',
		'typescript/no-unsafe-declaration-merging': 'error',
		'typescript/no-unsafe-function-type': 'error',
		'typescript/no-unused-expressions': [
			'error',
			{
				allowShortCircuit: true,
				allowTaggedTemplates: true,
				allowTernary: true,
			},
		],
		'typescript/no-var-requires': 'error',
		'typescript/no-wrapper-object-types': 'error',
		'typescript/prefer-as-const': 'error',
		'typescript/prefer-namespace-keyword': 'error',
		'typescript/prefer-optional-chain': 'error',
		'typescript/restrict-template-expressions': [
			'error',
			{
				allowNumber: true,
			},
		],
		'typescript/triple-slash-reference': 'error',
		'typescript/unbound-method': 'off',
		'unicode-bom': 'error',
		'unicorn/catch-error-name': 'error',
		'unicorn/consistent-empty-array-spread': 'error',
		'unicorn/consistent-function-scoping': 'error',
		'unicorn/no-abusive-eslint-disable': 'error',
		'unicorn/no-hex-escape': 'error',
		'unicorn/no-invalid-fetch-options': 'error',
		'unicorn/no-magic-array-flat-depth': 'error',
		'unicorn/no-null': 'off',
		'unicorn/no-typeof-undefined': 'error',
		'unicorn/no-unnecessary-slice-end': 'error',
		'unicorn/no-useless-promise-resolve-reject': 'error',
		'unicorn/no-useless-spread': 'error',
		'unicorn/numeric-separators-style': 'error',
		'unicorn/prefer-array-flat-map': 'error',
		'unicorn/prefer-array-index-of': 'error',
		'unicorn/prefer-array-some': 'error',
		'unicorn/prefer-at': 'error',
		'unicorn/prefer-dom-node-append': 'error',
		'unicorn/prefer-native-coercion-functions': 'error',
		'unicorn/prefer-node-protocol': 'error',
		'unicorn/prefer-number-properties': 'error',
		'unicorn/prefer-optional-catch-binding': 'error',
		'unicorn/prefer-set-size': 'error',
		'unicorn/prefer-string-raw': 'error',
		'unicorn/prefer-string-replace-all': 'error',
		'unicorn/prefer-string-slice': 'error',
		'unicorn/prefer-structured-clone': 'error',
		'unicorn/prefer-top-level-await': 'error',
		'unicorn/text-encoding-identifier-case': 'error',
		'use-isnan': 'error',
		'valid-jsdoc': 'off',
		'valid-typeof': 'error',
	},
})
