// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://kinopoiskapiunofficial.tech' | (string & {});
};

export type Film = {
    kinopoiskId: number;
    kinopoiskHDId: string | null;
    imdbId: string | null;
    nameRu: string | null;
    nameEn: string | null;
    nameOriginal: string | null;
    posterUrl: string;
    posterUrlPreview: string;
    coverUrl: string | null;
    logoUrl: string | null;
    reviewsCount: number;
    ratingGoodReview: number | null;
    ratingGoodReviewVoteCount: number | null;
    ratingKinopoisk: number | null;
    ratingKinopoiskVoteCount: number | null;
    ratingImdb: number | null;
    ratingImdbVoteCount: number | null;
    ratingFilmCritics: number | null;
    ratingFilmCriticsVoteCount: number | null;
    ratingAwait: number | null;
    ratingAwaitCount: number | null;
    ratingRfCritics: number | null;
    ratingRfCriticsVoteCount: number | null;
    webUrl: string;
    year: number | null;
    filmLength: number | null;
    slogan: string | null;
    description: string | null;
    shortDescription: string | null;
    editorAnnotation: string | null;
    isTicketsAvailable: boolean;
    productionStatus: 'FILMING' | 'PRE_PRODUCTION' | 'COMPLETED' | 'ANNOUNCED' | 'UNKNOWN' | 'POST_PRODUCTION';
    type: 'FILM' | 'VIDEO' | 'TV_SERIES' | 'MINI_SERIES' | 'TV_SHOW';
    ratingMpaa: string | null;
    ratingAgeLimits: string | null;
    hasImax: boolean | null;
    has3D: boolean | null;
    lastSync: string;
    countries: Array<Country>;
    genres: Array<Genre>;
    startYear: number | null;
    endYear: number | null;
    serial?: boolean | null;
    shortFilm?: boolean | null;
    completed?: boolean | null;
};

export type SeasonResponse = {
    total: number;
    items: Array<Season>;
};

export type FactResponse = {
    total: number;
    items: Array<Fact>;
};

export type DistributionResponse = {
    total: number;
    items: Array<Distribution>;
};

export type BoxOfficeResponse = {
    total: number;
    items: Array<BoxOffice>;
};

export type Fact = {
    text: string;
    type: 'FACT' | 'BLOOPER';
    spoiler: boolean;
};

export type BoxOffice = {
    type: string;
    amount: number;
    currencyCode: string;
    name: string;
    symbol: string;
};

export type AwardResponse = {
    total: number;
    items: Array<Award>;
};

export type Award = {
    name: string;
    win: boolean;
    imageUrl: string | null;
    nominationName: string;
    year: number;
    persons?: Array<AwardPerson>;
};

export type AwardPerson = {
    kinopoiskId: number;
    webUrl: string;
    nameRu: string | null;
    nameEn: string | null;
    sex: string;
    posterUrl: string;
    growth: number | null;
    birthday: string | null;
    death: string | null;
    age: number | null;
    birthplace: string | null;
    deathplace: string | null;
    profession: string | null;
};

export type Distribution = {
    type: 'LOCAL' | 'COUNTRY_SPECIFIC' | 'PREMIERE' | 'ALL' | 'WORLD_PREMIER';
    subType: 'CINEMA' | 'DVD' | 'DIGITAL' | 'BLURAY';
    date: string | null;
    reRelease: boolean | null;
    country: Country & unknown;
    companies: Array<Company>;
};

export type Company = {
    name: string;
};

export type Season = {
    number: number;
    episodes: Array<Episode>;
};

export type Episode = {
    seasonNumber: number;
    episodeNumber: number;
    nameRu: string | null;
    nameEn: string | null;
    synopsis: string | null;
    releaseDate: string | null;
};

export type Country = {
    country: string;
};

export type Genre = {
    genre: string;
};

export type FiltersResponse = {
    genres: Array<FiltersResponseGenres>;
    countries: Array<FiltersResponseCountries>;
};

export type FilmSearchResponse = {
    keyword: string;
    pagesCount: number;
    searchFilmsCountResult: number;
    films: Array<FilmSearchResponseFilms>;
};

export type FilmSearchByFiltersResponse = {
    total: number;
    totalPages: number;
    items: Array<FilmSearchByFiltersResponseItems>;
};

export type FilmSequelsAndPrequelsResponse = {
    filmId: number;
    nameRu: string;
    nameEn: string;
    nameOriginal: string;
    posterUrl: string;
    posterUrlPreview: string;
    relationType: 'SEQUEL' | 'PREQUEL' | 'REMAKE' | 'UNKNOWN';
};

export type SimilarFilmResponse = {
    total: number;
    items: Array<SimilarFilmResponseItems>;
};

export type RelatedFilmResponse = {
    total: number;
    items: Array<RelatedFilmResponseItems>;
};

export type ReviewResponse = {
    /**
     * Суммарное кол-во пользовательских рецензий
     */
    total: number;
    totalPages: number;
    totalPositiveReviews: number;
    totalNegativeReviews: number;
    totalNeutralReviews: number;
    items: Array<ReviewResponseItems>;
};

export type ExternalSourceResponse = {
    /**
     * Суммарное кол-во сайтов
     */
    total: number;
    items: Array<ExternalSourceResponseItems>;
};

export type FilmCollectionResponse = {
    total: number;
    totalPages: number;
    items: Array<FilmCollectionResponseItems>;
};

export type StaffResponse = {
    staffId: number;
    nameRu: string | null;
    nameEn: string | null;
    description: string | null;
    posterUrl: string;
    professionText: string;
    professionKey: 'WRITER' | 'OPERATOR' | 'EDITOR' | 'COMPOSER' | 'PRODUCER_USSR' | 'TRANSLATOR' | 'DIRECTOR' | 'DESIGN' | 'PRODUCER' | 'ACTOR' | 'VOICE_DIRECTOR' | 'UNKNOWN';
};

export type PersonResponse = {
    personId: number;
    webUrl: string | null;
    nameRu: string | null;
    nameEn: string | null;
    sex: 'MALE' | 'FEMALE';
    posterUrl: string;
    growth: string | null;
    birthday: string | null;
    death: string | null;
    age: number | null;
    birthplace: string | null;
    deathplace: string | null;
    hasAwards: number | null;
    profession: string | null;
    facts: Array<string>;
    spouses: Array<PersonResponseSpouses>;
    films: Array<PersonResponseFilms>;
};

export type PersonByNameResponse = {
    total: number;
    items: Array<PersonByNameResponseItems>;
};

export type ImageResponse = {
    /**
     * Общее кол-во изображений
     */
    total: number;
    /**
     * Код-во доступных страниц
     */
    totalPages: number;
    items: Array<ImageResponseItems>;
};

export type PremiereResponse = {
    total: number;
    items: Array<PremiereResponseItem>;
};

export type PremiereResponseItem = {
    kinopoiskId: number;
    nameRu: string | null;
    nameEn: string | null;
    year: number;
    posterUrl: string;
    posterUrlPreview: string;
    countries: Array<Country>;
    genres: Array<Genre>;
    duration: number | null;
    premiereRu: string;
};

export type DigitalReleaseResponse = {
    page: number;
    total: number;
    releases: Array<DigitalReleaseItem>;
};

export type DigitalReleaseItem = {
    filmId: number;
    nameRu: string;
    nameEn: string;
    year: number;
    posterUrl: string;
    posterUrlPreview: string;
    countries: Array<Country>;
    genres: Array<Genre>;
    rating: number;
    ratingVoteCount: number;
    expectationsRating: number;
    expectationsRatingVoteCount: number;
    duration: number;
    releaseDate: string;
};

export type VideoResponse = {
    total: number;
    items: Array<VideoResponseItems>;
};

export type KinopoiskUserVoteResponse = {
    total: number;
    totalPages: number;
    items: Array<KinopoiskUserVoteResponseItems>;
};

export type ApiKeyResponse = {
    totalQuota: ApiKeyResponseTotalQuota;
    dailyQuota: ApiKeyResponseDailyQuota;
    accountType: 'FREE' | 'EXTENDED' | 'UNLIMITED';
};

export type MediaPostsResponse = {
    total: number;
    totalPages: number;
    items: Array<MediaPostsResponseItems>;
};

export type ApiError = {
    message: string;
};

export type FiltersResponseGenres = {
    id?: number;
    genre?: string;
};

export type FiltersResponseCountries = {
    id?: number;
    country?: string;
};

export type FilmSearchResponseFilms = {
    filmId?: number;
    nameRu?: string;
    nameEn?: string;
    type?: 'FILM' | 'TV_SHOW' | 'VIDEO' | 'MINI_SERIES' | 'TV_SERIES' | 'UNKNOWN';
    year?: string;
    description?: string;
    filmLength?: string;
    countries?: Array<Country>;
    genres?: Array<Genre>;
    rating?: string;
    ratingVoteCount?: number;
    posterUrl?: string;
    posterUrlPreview?: string;
};

export type FilmSearchByFiltersResponseItems = {
    kinopoiskId?: number;
    imdbId?: string | null;
    nameRu?: string | null;
    nameEn?: string | null;
    nameOriginal?: string | null;
    countries?: Array<Country>;
    genres?: Array<Genre>;
    ratingKinopoisk?: number | null;
    ratingImdb?: number | null;
    year?: number | null;
    type?: 'FILM' | 'TV_SHOW' | 'VIDEO' | 'MINI_SERIES' | 'TV_SERIES' | 'UNKNOWN';
    posterUrl?: string;
    posterUrlPreview?: string;
};

export type SimilarFilmResponseItems = {
    filmId?: number;
    nameRu?: string | null;
    nameEn?: string | null;
    nameOriginal?: string | null;
    posterUrl?: string;
    posterUrlPreview?: string;
    relationType?: 'SIMILAR';
};

export type RelatedFilmResponseItems = {
    kinopoiskId?: number;
    nameRu?: string | null;
    nameEn?: string | null;
    nameOriginal?: string | null;
    posterUrl?: string;
    posterUrlPreview?: string;
    relationType?: 'SEQUEL' | 'PREQUEL' | 'REMAKE' | 'SIMILAR' | 'VERSION' | 'SPOOFS' | 'SPOOFED' | 'SPIN_OFF' | 'SPUN_OFF_FROM' | 'REFERENCES' | 'REFERENCES_IN' | 'EDITED_FROM' | 'EDITED_INTO' | 'ALTERNATE_LANGUAGE';
};

export type ReviewResponseItems = {
    kinopoiskId?: number;
    type?: 'POSITIVE' | 'NEGATIVE' | 'NEUTRAL' | 'UNKNOWN';
    date?: string;
    positiveRating?: number;
    negativeRating?: number;
    author?: string;
    title?: string | null;
    description?: string;
};

export type ExternalSourceResponseItems = {
    url?: string;
    platform?: string;
    logoUrl?: string;
    positiveRating?: number;
    negativeRating?: number;
    author?: string;
    title?: string | null;
    description?: string;
};

export type FilmCollectionResponseItems = {
    kinopoiskId?: number;
    nameRu?: string | null;
    nameEn?: string | null;
    nameOriginal?: string | null;
    countries?: Array<Country>;
    genres?: Array<Genre>;
    ratingKinopoisk?: number | null;
    ratingImbd?: number | null;
    year?: string | null;
    type?: 'FILM' | 'TV_SHOW' | 'VIDEO' | 'MINI_SERIES' | 'TV_SERIES' | 'UNKNOWN';
    posterUrl?: string;
    posterUrlPreview?: string;
};

export type PersonResponseSpouses = {
    personId?: number;
    name?: string | null;
    divorced?: boolean;
    divorcedReason?: string | null;
    sex?: 'MALE' | 'FEMALE';
    children?: number;
    webUrl?: string;
    relation?: string;
};

export type PersonResponseFilms = {
    filmId?: number;
    nameRu?: string | null;
    nameEn?: string | null;
    rating?: string | null;
    general?: boolean;
    description?: string | null;
    professionKey?: 'WRITER' | 'OPERATOR' | 'EDITOR' | 'COMPOSER' | 'PRODUCER_USSR' | 'HIMSELF' | 'HERSELF' | 'HRONO_TITR_MALE' | 'HRONO_TITR_FEMALE' | 'TRANSLATOR' | 'DIRECTOR' | 'DESIGN' | 'PRODUCER' | 'ACTOR' | 'VOICE_DIRECTOR' | 'UNKNOWN';
};

export type PersonByNameResponseItems = {
    kinopoiskId?: number;
    webUrl?: string;
    nameRu?: string | null;
    nameEn?: string | null;
    sex?: 'MALE' | 'FEMALE' | 'UNKNOWN';
    posterUrl?: string;
};

export type ImageResponseItems = {
    imageUrl?: string;
    previewUrl?: string;
};

export type VideoResponseItems = {
    url?: string;
    name?: string;
    site?: 'YOUTUBE' | 'KINOPOISK_WIDGET' | 'YANDEX_DISK' | 'UNKNOWN';
};

export type KinopoiskUserVoteResponseItems = {
    kinopoiskId?: number;
    nameRu?: string | null;
    nameEn?: string | null;
    nameOriginal?: string | null;
    countries?: Array<Country>;
    genres?: Array<Genre>;
    ratingKinopoisk?: number | null;
    ratingImbd?: number | null;
    year?: string | null;
    type?: 'FILM' | 'TV_SHOW' | 'VIDEO' | 'MINI_SERIES' | 'TV_SERIES' | 'UNKNOWN';
    posterUrl?: string;
    posterUrlPreview?: string;
    userRating?: number;
};

export type ApiKeyResponseTotalQuota = {
    value: number;
    used: number;
};

export type ApiKeyResponseDailyQuota = {
    value: number;
    used: number;
};

export type MediaPostsResponseItems = {
    kinopoiskId?: number;
    imageUrl?: string;
    title?: string;
    description?: string;
    url?: string;
    publishedAt?: string;
};

export type GetApiV22FilmsByIdData = {
    body?: never;
    path: {
        /**
         * kinopoisk film id
         */
        id: number;
    };
    query?: never;
    url: '/api/v2.2/films/{id}';
};

export type GetApiV22FilmsByIdErrors = {
    /**
     * Пустой или неправильный токен
     */
    401: unknown;
    /**
     * Превышен лимит запросов(или дневной, или общий)
     */
    402: unknown;
    /**
     * Фильм не найден
     */
    404: unknown;
    /**
     * Слишком много запросов. Общий лимит - 20 запросов в секунду
     */
    429: unknown;
};

export type GetApiV22FilmsByIdResponses = {
    /**
     * Запрос выполнен успешно
     */
    200: Film;
};

export type GetApiV22FilmsByIdResponse = GetApiV22FilmsByIdResponses[keyof GetApiV22FilmsByIdResponses];

export type GetApiV22FilmsByIdSeasonsData = {
    body?: never;
    path: {
        /**
         * kinopoisk film id
         */
        id: number;
    };
    query?: never;
    url: '/api/v2.2/films/{id}/seasons';
};

export type GetApiV22FilmsByIdSeasonsErrors = {
    /**
     * Пустой или неправильный токен
     */
    401: unknown;
    /**
     * Превышен лимит запросов(или дневной, или общий)
     */
    402: unknown;
    /**
     * Слишком много запросов. Общий лимит - 20 запросов в секунду
     */
    429: unknown;
};

export type GetApiV22FilmsByIdSeasonsResponses = {
    /**
     * Запрос выполнен успешно
     */
    200: SeasonResponse;
};

export type GetApiV22FilmsByIdSeasonsResponse = GetApiV22FilmsByIdSeasonsResponses[keyof GetApiV22FilmsByIdSeasonsResponses];

export type GetApiV22FilmsByIdFactsData = {
    body?: never;
    path: {
        /**
         * kinopoisk film id
         */
        id: number;
    };
    query?: never;
    url: '/api/v2.2/films/{id}/facts';
};

export type GetApiV22FilmsByIdFactsErrors = {
    /**
     * Пустой или неправильный токен
     */
    401: unknown;
    /**
     * Превышен лимит запросов(или дневной, или общий)
     */
    402: unknown;
    /**
     * Слишком много запросов. Общий лимит - 20 запросов в секунду
     */
    429: unknown;
};

export type GetApiV22FilmsByIdFactsResponses = {
    /**
     * Запрос выполнен успешно
     */
    200: FactResponse;
};

export type GetApiV22FilmsByIdFactsResponse = GetApiV22FilmsByIdFactsResponses[keyof GetApiV22FilmsByIdFactsResponses];

export type GetApiV22FilmsByIdDistributionsData = {
    body?: never;
    path: {
        /**
         * kinopoisk film id
         */
        id: number;
    };
    query?: never;
    url: '/api/v2.2/films/{id}/distributions';
};

export type GetApiV22FilmsByIdDistributionsErrors = {
    /**
     * Пустой или неправильный токен
     */
    401: unknown;
    /**
     * Превышен лимит запросов(или дневной, или общий)
     */
    402: unknown;
    /**
     * Слишком много запросов. Общий лимит - 20 запросов в секунду
     */
    429: unknown;
};

export type GetApiV22FilmsByIdDistributionsResponses = {
    /**
     * Запрос выполнен успешно
     */
    200: DistributionResponse;
};

export type GetApiV22FilmsByIdDistributionsResponse = GetApiV22FilmsByIdDistributionsResponses[keyof GetApiV22FilmsByIdDistributionsResponses];

export type GetApiV22FilmsByIdBoxOfficeData = {
    body?: never;
    path: {
        /**
         * kinopoisk film id
         */
        id: number;
    };
    query?: never;
    url: '/api/v2.2/films/{id}/box_office';
};

export type GetApiV22FilmsByIdBoxOfficeErrors = {
    /**
     * Пустой или неправильный токен
     */
    401: unknown;
    /**
     * Превышен лимит запросов(или дневной, или общий)
     */
    402: unknown;
    /**
     * Слишком много запросов. Общий лимит - 20 запросов в секунду
     */
    429: unknown;
};

export type GetApiV22FilmsByIdBoxOfficeResponses = {
    /**
     * Запрос выполнен успешно
     */
    200: BoxOfficeResponse;
};

export type GetApiV22FilmsByIdBoxOfficeResponse = GetApiV22FilmsByIdBoxOfficeResponses[keyof GetApiV22FilmsByIdBoxOfficeResponses];

export type GetApiV22FilmsByIdAwardsData = {
    body?: never;
    path: {
        /**
         * kinopoisk film id
         */
        id: number;
    };
    query?: never;
    url: '/api/v2.2/films/{id}/awards';
};

export type GetApiV22FilmsByIdAwardsErrors = {
    /**
     * Пустой или неправильный токен
     */
    401: unknown;
    /**
     * Превышен лимит запросов(или дневной, или общий)
     */
    402: unknown;
    /**
     * Слишком много запросов. Общий лимит - 20 запросов в секунду
     */
    429: unknown;
};

export type GetApiV22FilmsByIdAwardsResponses = {
    /**
     * Запрос выполнен успешно
     */
    200: AwardResponse;
};

export type GetApiV22FilmsByIdAwardsResponse = GetApiV22FilmsByIdAwardsResponses[keyof GetApiV22FilmsByIdAwardsResponses];

export type GetApiV22FilmsByIdVideosData = {
    body?: never;
    path: {
        /**
         * kinopoisk film id
         */
        id: number;
    };
    query?: never;
    url: '/api/v2.2/films/{id}/videos';
};

export type GetApiV22FilmsByIdVideosErrors = {
    /**
     * Пустой или неправильный токен
     */
    401: unknown;
    /**
     * Превышен лимит запросов(или дневной, или общий)
     */
    402: unknown;
    /**
     * Слишком много запросов. Общий лимит - 20 запросов в секунду
     */
    429: unknown;
};

export type GetApiV22FilmsByIdVideosResponses = {
    /**
     * Запрос выполнен успешно
     */
    200: VideoResponse;
};

export type GetApiV22FilmsByIdVideosResponse = GetApiV22FilmsByIdVideosResponses[keyof GetApiV22FilmsByIdVideosResponses];

export type GetApiV22FilmsByIdSimilarsData = {
    body?: never;
    path: {
        /**
         * kinopoisk film id
         */
        id: number;
    };
    query?: never;
    url: '/api/v2.2/films/{id}/similars';
};

export type GetApiV22FilmsByIdSimilarsErrors = {
    /**
     * Пустой или неправильный токен
     */
    401: unknown;
    /**
     * Превышен лимит запросов(или дневной, или общий)
     */
    402: unknown;
    /**
     * Слишком много запросов. Общий лимит - 20 запросов в секунду
     */
    429: unknown;
};

export type GetApiV22FilmsByIdSimilarsResponses = {
    /**
     * Запрос выполнен успешно
     */
    200: SimilarFilmResponse;
};

export type GetApiV22FilmsByIdSimilarsResponse = GetApiV22FilmsByIdSimilarsResponses[keyof GetApiV22FilmsByIdSimilarsResponses];

export type GetApiV22FilmsByIdRelationsData = {
    body?: never;
    path: {
        /**
         * kinopoisk film id
         */
        id: number;
    };
    query?: never;
    url: '/api/v2.2/films/{id}/relations';
};

export type GetApiV22FilmsByIdRelationsErrors = {
    /**
     * Пустой или неправильный токен
     */
    401: unknown;
    /**
     * Превышен лимит запросов(или дневной, или общий)
     */
    402: unknown;
    /**
     * Слишком много запросов. Общий лимит - 20 запросов в секунду
     */
    429: unknown;
};

export type GetApiV22FilmsByIdRelationsResponses = {
    /**
     * Запрос выполнен успешно
     */
    200: RelatedFilmResponse;
};

export type GetApiV22FilmsByIdRelationsResponse = GetApiV22FilmsByIdRelationsResponses[keyof GetApiV22FilmsByIdRelationsResponses];

export type GetApiV22FilmsByIdImagesData = {
    body?: never;
    path: {
        /**
         * kinopoisk film id
         */
        id: number;
    };
    query?: {
        /**
         * тип изображения
         */
        type?: 'STILL' | 'SHOOTING' | 'POSTER' | 'FAN_ART' | 'PROMO' | 'CONCEPT' | 'WALLPAPER' | 'COVER' | 'SCREENSHOT';
        /**
         * номер страницы
         */
        page?: number;
    };
    url: '/api/v2.2/films/{id}/images';
};

export type GetApiV22FilmsByIdImagesErrors = {
    /**
     * Пустой или неправильный токен
     */
    401: unknown;
    /**
     * Превышен лимит запросов(или дневной, или общий)
     */
    402: unknown;
    /**
     * Слишком много запросов. Общий лимит - 20 запросов в секунду
     */
    429: unknown;
};

export type GetApiV22FilmsByIdImagesResponses = {
    /**
     * Запрос выполнен успешно
     */
    200: ImageResponse;
};

export type GetApiV22FilmsByIdImagesResponse = GetApiV22FilmsByIdImagesResponses[keyof GetApiV22FilmsByIdImagesResponses];

export type GetApiV22FilmsByIdReviewsData = {
    body?: never;
    path: {
        /**
         * kinopoisk film id
         */
        id: number;
    };
    query?: {
        /**
         * номер страницы
         */
        page?: number;
        /**
         * тип сортировки
         */
        order?: 'DATE_ASC' | 'DATE_DESC' | 'USER_POSITIVE_RATING_ASC' | 'USER_POSITIVE_RATING_DESC' | 'USER_NEGATIVE_RATING_ASC' | 'USER_NEGATIVE_RATING_DESC';
    };
    url: '/api/v2.2/films/{id}/reviews';
};

export type GetApiV22FilmsByIdReviewsErrors = {
    /**
     * Пустой или неправильный токен
     */
    401: unknown;
    /**
     * Превышен лимит запросов(или дневной, или общий)
     */
    402: unknown;
    /**
     * Слишком много запросов. Общий лимит - 20 запросов в секунду
     */
    429: unknown;
};

export type GetApiV22FilmsByIdReviewsResponses = {
    /**
     * Запрос выполнен успешно
     */
    200: ReviewResponse;
};

export type GetApiV22FilmsByIdReviewsResponse = GetApiV22FilmsByIdReviewsResponses[keyof GetApiV22FilmsByIdReviewsResponses];

export type GetApiV22FilmsByIdExternalSourcesData = {
    body?: never;
    path: {
        /**
         * kinopoisk film id
         */
        id: number;
    };
    query?: {
        /**
         * номер страницы
         */
        page?: number;
    };
    url: '/api/v2.2/films/{id}/external_sources';
};

export type GetApiV22FilmsByIdExternalSourcesErrors = {
    /**
     * Пустой или неправильный токен
     */
    401: unknown;
    /**
     * Превышен лимит запросов(или дневной, или общий)
     */
    402: unknown;
    /**
     * Слишком много запросов. Общий лимит - 20 запросов в секунду
     */
    429: unknown;
};

export type GetApiV22FilmsByIdExternalSourcesResponses = {
    /**
     * Запрос выполнен успешно
     */
    200: ExternalSourceResponse;
};

export type GetApiV22FilmsByIdExternalSourcesResponse = GetApiV22FilmsByIdExternalSourcesResponses[keyof GetApiV22FilmsByIdExternalSourcesResponses];

export type GetApiV22FilmsCollectionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * тип топа или коллекции
         */
        type?: 'TOP_POPULAR_ALL' | 'TOP_POPULAR_MOVIES' | 'TOP_250_TV_SHOWS' | 'TOP_250_MOVIES' | 'VAMPIRE_THEME' | 'COMICS_THEME' | 'CLOSES_RELEASES' | 'FAMILY' | 'OSKAR_WINNERS_2021' | 'LOVE_THEME' | 'ZOMBIE_THEME' | 'CATASTROPHE_THEME' | 'KIDS_ANIMATION_THEME' | 'POPULAR_SERIES';
        /**
         * номер страницы
         */
        page?: number;
    };
    url: '/api/v2.2/films/collections';
};

export type GetApiV22FilmsCollectionsErrors = {
    /**
     * Пустой или неправильный токен
     */
    401: unknown;
    /**
     * Превышен лимит запросов(или дневной, или общий)
     */
    402: unknown;
    /**
     * Слишком много запросов. Лимит 5 запроса в секунду
     */
    429: unknown;
};

export type GetApiV22FilmsCollectionsResponses = {
    /**
     * Запрос выполнен успешно
     */
    200: FilmCollectionResponse;
};

export type GetApiV22FilmsCollectionsResponse = GetApiV22FilmsCollectionsResponses[keyof GetApiV22FilmsCollectionsResponses];

export type GetApiV22FilmsPremieresData = {
    body?: never;
    path?: never;
    query: {
        /**
         * год релиза
         */
        year: number;
        /**
         * месяц релиза
         */
        month: 'JANUARY' | 'FEBRUARY' | 'MARCH' | 'APRIL' | 'MAY' | 'JUNE' | 'JULY' | 'AUGUST' | 'SEPTEMBER' | 'OCTOBER' | 'NOVEMBER' | 'DECEMBER';
    };
    url: '/api/v2.2/films/premieres';
};

export type GetApiV22FilmsPremieresErrors = {
    /**
     * Пустой или неправильный токен
     */
    401: unknown;
    /**
     * Превышен лимит запросов(или дневной, или общий)
     */
    402: unknown;
    /**
     * Слишком много запросов. Лимит 5 запросов в секунду
     */
    429: unknown;
};

export type GetApiV22FilmsPremieresResponses = {
    /**
     * Запрос выполнен успешно
     */
    200: PremiereResponse;
};

export type GetApiV22FilmsPremieresResponse = GetApiV22FilmsPremieresResponses[keyof GetApiV22FilmsPremieresResponses];

export type GetApiV22FilmsFiltersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v2.2/films/filters';
};

export type GetApiV22FilmsFiltersErrors = {
    /**
     * Пустой или неправильный токен
     */
    401: unknown;
    /**
     * Превышен лимит запросов(или дневной, или общий)
     */
    402: unknown;
    /**
     * Слишком много запросов. Общий лимит - 20 запросов в секунду
     */
    429: unknown;
};

export type GetApiV22FilmsFiltersResponses = {
    /**
     * Запрос выполнен успешно
     */
    200: FiltersResponse;
};

export type GetApiV22FilmsFiltersResponse = GetApiV22FilmsFiltersResponses[keyof GetApiV22FilmsFiltersResponses];

export type GetApiV22FilmsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * список id стран разделенные запятой. Например <i>countries=1,2,3</i>. На данный момент можно указать не более одной страны.
         */
        countries?: Array<number>;
        /**
         * список id жанров разделенные запятой. Например <i>genres=1,2,3</i>. На данный момент можно указать не более одного жанра.
         */
        genres?: Array<number>;
        /**
         * сортировка
         */
        order?: 'RATING' | 'NUM_VOTE' | 'YEAR';
        /**
         * тип фильма
         */
        type?: 'FILM' | 'TV_SHOW' | 'TV_SERIES' | 'MINI_SERIES' | 'ALL';
        /**
         * минимальный рейтинг
         */
        ratingFrom?: number;
        /**
         * максимальный рейтинг
         */
        ratingTo?: number;
        /**
         * минимальный год
         */
        yearFrom?: number;
        /**
         * максимальный год
         */
        yearTo?: number;
        /**
         * imdb id
         */
        imdbId?: string;
        /**
         * ключевое слово, которое встречается в названии фильма
         */
        keyword?: string;
        /**
         * номер страницы
         */
        page?: number;
    };
    url: '/api/v2.2/films';
};

export type GetApiV22FilmsErrors = {
    /**
     * Пустой или неправильный токен
     */
    401: unknown;
    /**
     * Превышен лимит запросов(или дневной, или общий)
     */
    402: unknown;
    /**
     * Слишком много запросов. Лимит 5 запросов в секунду
     */
    429: unknown;
};

export type GetApiV22FilmsResponses = {
    /**
     * Запрос выполнен успешно
     */
    200: FilmSearchByFiltersResponse;
};

export type GetApiV22FilmsResponse = GetApiV22FilmsResponses[keyof GetApiV22FilmsResponses];

export type GetApiV21FilmsByIdSequelsAndPrequelsData = {
    body?: never;
    path: {
        /**
         * kinopoisk film id
         */
        id: number;
    };
    query?: never;
    url: '/api/v2.1/films/{id}/sequels_and_prequels';
};

export type GetApiV21FilmsByIdSequelsAndPrequelsErrors = {
    /**
     * Пустой или неправильный токен
     */
    401: unknown;
    /**
     * Превышен лимит запросов(или дневной, или общий)
     */
    402: unknown;
    /**
     * Фильм не найден
     */
    404: unknown;
    /**
     * Слишком много запросов. Общий лимит - 20 запросов в секунду
     */
    429: unknown;
};

export type GetApiV21FilmsByIdSequelsAndPrequelsResponses = {
    /**
     * Запрос выполнен успешно
     */
    200: Array<FilmSequelsAndPrequelsResponse>;
};

export type GetApiV21FilmsByIdSequelsAndPrequelsResponse = GetApiV21FilmsByIdSequelsAndPrequelsResponses[keyof GetApiV21FilmsByIdSequelsAndPrequelsResponses];

export type GetApiV21FilmsSearchByKeywordData = {
    body?: never;
    path?: never;
    query: {
        /**
         * ключивые слова для поиска
         */
        keyword: string;
        /**
         * номер страницы
         */
        page?: number;
    };
    url: '/api/v2.1/films/search-by-keyword';
};

export type GetApiV21FilmsSearchByKeywordErrors = {
    /**
     * Пустой или неправильный токен
     */
    401: unknown;
    /**
     * Превышен лимит запросов(или дневной, или общий)
     */
    402: unknown;
    /**
     * Фильмы не найдены
     */
    404: unknown;
    /**
     * Слишком много запросов. Лимит 5 запросов в секунду
     */
    429: unknown;
};

export type GetApiV21FilmsSearchByKeywordResponses = {
    /**
     * Запрос выполнен успешно
     */
    200: FilmSearchResponse;
};

export type GetApiV21FilmsSearchByKeywordResponse = GetApiV21FilmsSearchByKeywordResponses[keyof GetApiV21FilmsSearchByKeywordResponses];

export type GetApiV1StaffData = {
    body?: never;
    path?: never;
    query: {
        /**
         * kinopoisk film id
         */
        filmId: number;
    };
    url: '/api/v1/staff';
};

export type GetApiV1StaffErrors = {
    /**
     * Пустой или неправильный токен
     */
    401: unknown;
    /**
     * Превышен лимит запросов(или дневной, или общий)
     */
    402: unknown;
    /**
     * Данные не найдены
     */
    404: unknown;
    /**
     * Слишком много запросов. Общий лимит - 20 запросов в секунду
     */
    429: unknown;
};

export type GetApiV1StaffResponses = {
    /**
     * Запрос выполнен успешно
     */
    200: Array<StaffResponse>;
};

export type GetApiV1StaffResponse = GetApiV1StaffResponses[keyof GetApiV1StaffResponses];

export type GetApiV1StaffByIdData = {
    body?: never;
    path: {
        /**
         * kinopoisk person id
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/staff/{id}';
};

export type GetApiV1StaffByIdErrors = {
    /**
     * Пустой или неправильный токен
     */
    401: unknown;
    /**
     * Превышен лимит запросов(или дневной, или общий)
     */
    402: unknown;
    /**
     * Данные не найдены
     */
    404: unknown;
    /**
     * Слишком много запросов. Общий лимит - 20 запросов в секунду
     */
    429: unknown;
};

export type GetApiV1StaffByIdResponses = {
    /**
     * Запрос выполнен успешно
     */
    200: PersonResponse;
};

export type GetApiV1StaffByIdResponse = GetApiV1StaffByIdResponses[keyof GetApiV1StaffByIdResponses];

export type GetApiV1PersonsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * имя человека
         */
        name: string;
        /**
         * номер страницы
         */
        page?: number;
    };
    url: '/api/v1/persons';
};

export type GetApiV1PersonsErrors = {
    /**
     * Пустой или неправильный токен
     */
    401: unknown;
    /**
     * Превышен лимит запросов(или дневной, или общий)
     */
    402: unknown;
    /**
     * Слишком много запросов. Общий лимит - 5 запросов в секунду
     */
    429: unknown;
};

export type GetApiV1PersonsResponses = {
    /**
     * Запрос выполнен успешно
     */
    200: PersonByNameResponse;
};

export type GetApiV1PersonsResponse = GetApiV1PersonsResponses[keyof GetApiV1PersonsResponses];

export type GetApiV1KpUsersByIdVotesData = {
    body?: never;
    path: {
        /**
         * id пользователя на сайте кинопоиск
         */
        id: number;
    };
    query?: {
        /**
         * номер страницы
         */
        page?: number;
    };
    url: '/api/v1/kp_users/{id}/votes';
};

export type GetApiV1KpUsersByIdVotesErrors = {
    /**
     * Пустой или неправильный токен
     */
    401: unknown;
    /**
     * Превышен лимит запросов(или дневной, или общий)
     */
    402: unknown;
    /**
     * Слишком много запросов. Общий лимит - 2 запросов в секунду
     */
    429: unknown;
};

export type GetApiV1KpUsersByIdVotesResponses = {
    /**
     * Запрос выполнен успешно
     */
    200: KinopoiskUserVoteResponse;
};

export type GetApiV1KpUsersByIdVotesResponse = GetApiV1KpUsersByIdVotesResponses[keyof GetApiV1KpUsersByIdVotesResponses];

export type GetApiV1ApiKeysByApiKeyData = {
    body?: never;
    path: {
        /**
         * api key
         */
        apiKey: string;
    };
    query?: never;
    url: '/api/v1/api_keys/{apiKey}';
};

export type GetApiV1ApiKeysByApiKeyErrors = {
    /**
     * Слишком много запросов. Общий лимит - 2 запросов в секунду
     */
    429: unknown;
};

export type GetApiV1ApiKeysByApiKeyResponses = {
    /**
     * Запрос выполнен успешно
     */
    200: ApiKeyResponse;
};

export type GetApiV1ApiKeysByApiKeyResponse = GetApiV1ApiKeysByApiKeyResponses[keyof GetApiV1ApiKeysByApiKeyResponses];

export type GetApiV1MediaPostsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * номер страницы
         */
        page?: number;
    };
    url: '/api/v1/media_posts';
};

export type GetApiV1MediaPostsErrors = {
    /**
     * Слишком много запросов. Общий лимит - 20 запросов в секунду
     */
    429: unknown;
};

export type GetApiV1MediaPostsResponses = {
    /**
     * Запрос выполнен успешно
     */
    200: MediaPostsResponse;
};

export type GetApiV1MediaPostsResponse = GetApiV1MediaPostsResponses[keyof GetApiV1MediaPostsResponses];
